//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalAuthor
    {
        public int AdditionalAuthorId { get; set; }
        public string Name { get; set; }
        public string Affiliation { get; set; }
        public int PaperId { get; set; }
    
        public virtual Paper Paper { get; set; }
    }
}
