//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int PCMemberUserId { get; set; }
        public int PCMemberConferenceId { get; set; }
        public int PaperId { get; set; }
        public int BiddingEvaluation { get; set; }
    
        public virtual PCMember PCMember { get; set; }
        public virtual Paper Paper { get; set; }
    }
}
