//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        public int ConferenceId { get; set; }
        public string Name { get; set; }
        public string Edition { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Website { get; set; }
        public int Price { get; set; }
        public System.DateTime DeadlineAbstractPaper { get; set; }
        public System.DateTime DeadlineCompletePaper { get; set; }
        public System.DateTime DeadlineBiddingPaper { get; set; }
        public System.DateTime DeadlineEvaluation { get; set; }
        public System.DateTime DeadlineParticipation { get; set; }
    }
}
