//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperReservation
    {
        public int PaperReservationId { get; set; }
        public Nullable<int> RoomReservationId { get; set; }
        public int PaperId { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public int Duration { get; set; }
    
        public virtual Paper Paper { get; set; }
        public virtual RoomReservation RoomReservation { get; set; }
    }
}
