//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paper()
        {
            this.AdditionalAuthors = new HashSet<AdditionalAuthor>();
            this.Bids = new HashSet<Bid>();
            this.PaperReservations = new HashSet<PaperReservation>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int PaperId { get; set; }
        public string Name { get; set; }
        public string Resume { get; set; }
        public string Domain { get; set; }
        public string Subdomain { get; set; }
        public string Filepath { get; set; }
        public string EvaluationResult { get; set; }
        public bool IsEmailSent { get; set; }
        public int ConferenceId { get; set; }
        public int UserId { get; set; }
        public int TopicId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalAuthor> AdditionalAuthors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual Conference Conference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperReservation> PaperReservations { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
