//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.RoomReservations = new HashSet<RoomReservation>();
        }
    
        public int SessionId { get; set; }
        public int ConferenceId { get; set; }
        public string Name { get; set; }
        public string Topic { get; set; }
        public int SessionChairId { get; set; }
        public int PCMemberConferenceId { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual PCMember PCMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservation> RoomReservations { get; set; }
    }
}
