//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ISSEntities2 : DbContext
    {
        public ISSEntities2()
            : base("name=ISSEntities2")
        {
        }

        public ISSEntities2(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<AdditionalAuthor> AdditionalAuthors { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AvailableRoom> AvailableRooms { get; set; }
        public virtual DbSet<Bid> Bids { get; set; }
        public virtual DbSet<ConferenceParticipant> ConferenceParticipants { get; set; }
        public virtual DbSet<Paper> Papers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PCMember> PCMembers { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    
        public virtual int insertUser(string username, string name, string password, string email, string affiliation, string webPage)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var affiliationParameter = affiliation != null ?
                new ObjectParameter("Affiliation", affiliation) :
                new ObjectParameter("Affiliation", typeof(string));
    
            var webPageParameter = webPage != null ?
                new ObjectParameter("WebPage", webPage) :
                new ObjectParameter("WebPage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertUser", usernameParameter, nameParameter, passwordParameter, emailParameter, affiliationParameter, webPageParameter);
        }
    
        public virtual int PopulatePaperReservations(Nullable<int> conferenceId, Nullable<int> duration)
        {
            var conferenceIdParameter = conferenceId.HasValue ?
                new ObjectParameter("ConferenceId", conferenceId) :
                new ObjectParameter("ConferenceId", typeof(int));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("Duration", duration) :
                new ObjectParameter("Duration", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PopulatePaperReservations", conferenceIdParameter, durationParameter);
        }
    
        public virtual int PopulateRoomReservations(Nullable<int> conferenceId)
        {
            var conferenceIdParameter = conferenceId.HasValue ?
                new ObjectParameter("ConferenceId", conferenceId) :
                new ObjectParameter("ConferenceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PopulateRoomReservations", conferenceIdParameter);
        }
    }
}
