//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conference()
        {
            this.Papers = new HashSet<Paper>();
            this.Topics = new HashSet<Topic>();
            this.Sections = new HashSet<Section>();
            this.ConferenceParticipants = new HashSet<ConferenceParticipant>();
            this.OrganizingComiteeMembers = new HashSet<OrganizingComiteeMember>();
        }
    
        public int ConferenceId { get; set; }
        public string Name { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Website { get; set; }
        public int Price { get; set; }
        public System.DateTime DeadlineAbstractPaper { get; set; }
        public System.DateTime DeadlineCompletePaper { get; set; }
        public System.DateTime DeadlineEvaluation { get; set; }
        public System.DateTime DeadlineParticipation { get; set; }
        public int Section_sectionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paper> Papers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceParticipant> ConferenceParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizingComiteeMember> OrganizingComiteeMembers { get; set; }
    }
}
