//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceParticipant
    {
        public string UserUsername { get; set; }
        public int ConferenceConferenceId { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual User User { get; set; }
        public virtual Conference Conference { get; set; }
    }
}
