//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperTag
    {
        public int PaperPaperId { get; set; }
        public int TagTagId { get; set; }
    
        public virtual Paper Paper { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
