//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomReservation()
        {
            this.PaperReservations = new HashSet<PaperReservation>();
        }
    
        public int RoomReservationId { get; set; }
        public int SectionSectionId { get; set; }
        public int RoomRoomId { get; set; }
        public System.TimeSpan BeginTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTime Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperReservation> PaperReservations { get; set; }
        public virtual Room Room { get; set; }
        public virtual Section Section { get; set; }
    }
}
