//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.RoomReservations = new HashSet<RoomReservation>();
        }
    
        public int SectionId { get; set; }
        public int ConferenceConferenceId { get; set; }
        public string OrganizingComiteeMemberUserUsername { get; set; }
        public int OrganizingComiteeMemberConferenceConferenceId { get; set; }
        public string Name { get; set; }
    
        public virtual Conference Conference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservation> RoomReservations { get; set; }
        public virtual OrganizingComiteeMember OrganizingComiteeMember { get; set; }
    }
}
